---
title: "Descomposiciones"
format: html
editor: visual
---
```{r}
library(tidyverse)
library(fpp3)
```

```{r}
medicinas <-  read.csv("medicinas.csv", stringsAsFactors = FALSE)
medicinas$fecha <- as.Date(medicinas$fecha, format = "%Y-%m-%d")
medicinas
```

```{r}
medicinas <- medicinas |>
  as_tsibble(index = fecha)
```

```{r}
medicinas |> 
  autoplot(Cost)

```
```{r}
medicinas <- medicinas %>%
  mutate(fecha = yearmonth(fecha)) %>%     
  as_tsibble(index = fecha) %>%
  arrange(fecha) %>%
  filter(!is.na(Cost), Cost > 0)
```


```{r}
#| warning: false

medicinas_dcmp <- medicinas |>
  model(dcmp_clasica = classical_decomposition(Cost, type = "multiplicative")) |>
  components()

medicinas_dcmp
  
```
```{r}
medicinas_dcmp |> 
  ggplot(aes(y = Cost, x = fecha)) +
  geom_line(color = "grey") +
  geom_line(aes(y = season_adjust), color = "blue")

medicinas_dcmp |> 
  autoplot()
```

```{r}
medicinas_stl <- medicinas |>
  model(stl = STL(log(Cost) ~trend(window = NULL) + season(window = "periodic"), robust = TRUE)) |>
  components()

medicinas_stl |>
  autoplot()
```



































